# Generated by Django 5.2b1 on 2025-06-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_item_main_image_itemimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="is_on_main",
            field=models.BooleanField(
                default=False, verbose_name="Показывать на главной"
            ),
        ),
    ]
